name = "linkventory-api"
main = "worker.py"
compatibility_date = "2024-12-01"
compatibility_flags = ["python_workers"]

[vars]
# Add your environment variables here
# MONGODB_URL = "your-mongodb-connection-string"
# JWT_SECRET = "your-jwt-secret"

# Python Workers configuration
[python]
# Python requirements will be auto-detected from requirements.txt
